server:
  port: 9051

spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enbled: true

  thymeleaf:
    prefix: classpath:/templetes/
    cache: false
    check-template-location: true